apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: lonelydm/deakin-sit323-calculator:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://root:password@mongo:27017/calculator-db?authSource=admin
